parameters:
#    crystal_web.example.class: Crystal\CrystalWebBundle\Example

services:
#    crystal_web.example:
#        class: %crystal_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
