admin_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AdminBundle:Default:index }


listProject:
    pattern:  /admin/list
    defaults: { _controller: CrystalAdminBundle:Projects:list }

addProject:
    pattern:  /admin/addProject
    defaults: { _controller: CrystalAdminBundle:Projects:add }

updateProject:
    pattern:  /admin/updateProject/{id}
    defaults: { _controller: CrystalAdminBundle:Projects:update }

ereaseProject:
    pattern:  /admin/ereaseProject/{id}
    defaults: { _controller: CrystalAdminBundle:Projects:erease }


listClients:
    pattern:  /Clients/listClients
    defaults: { _controller: CrystalAdminBundle:Clients:list }

addClients:
    pattern:  /Clients/addClients
    defaults: { _controller: CrystalAdminBundle:Clients:add }

updateClients:
    pattern:  /Clients/updateClients/{id}
    defaults: { _controller: CrystalAdminBundle:Clients:update }

ereaseClients:
    pattern:  /Clients/ereaseClients/{id}
    defaults: { _controller: CrystalAdminBundle:Clients:erease }


listContactUs:
    pattern:  /Contactenos/listContactUs
    defaults: { _controller: CrystalAdminBundle:ContactUs:list }

addContactUs:
    pattern:  /Contactenos/addContactUs
    defaults: { _controller: CrystalAdminBundle:ContactUs:add }

updateContactUs:
    pattern:  /Contactenos/updateContactUs/{id}
    defaults: { _controller: CrystalAdminBundle:ContactUs:update }

ereaseContactUs:
    pattern:  /Contactenos/ereaseContactUs/{id}
    defaults: { _controller: CrystalAdminBundle:ContactUs:erease }


listAboutUs:
    pattern:  /Nosotros/listAboutUs
    defaults: { _controller: CrystalAdminBundle:AboutUs:list }

addAboutUs:
    pattern:  /Nosotros/addAboutUs
    defaults: { _controller: CrystalAdminBundle:AboutUs:add }

updateAboutUs:
    pattern:  /Nosotros/updateAboutUs/{id}
    defaults: { _controller: CrystalAdminBundle:AboutUs:update }

ereaseAboutUs:
    pattern:  /Nosotros/ereaseAboutUs/{id}
    defaults: { _controller: CrystalAdminBundle:AboutUs:erease }


listFounders:
    pattern:  /Fundadores/listFounders
    defaults: { _controller: CrystalAdminBundle:Founders:list }

addFounders:
    pattern:  /Fundadores/addFounders
    defaults: { _controller: CrystalAdminBundle:Founders:add }

updateFounders:
    pattern:  /Fundadores/updateFounders/{id}
    defaults: { _controller: CrystalAdminBundle:Founders:update }

ereaseFounders:
    pattern:  /Fundadores/ereaseFounders/{id}
    defaults: { _controller: CrystalAdminBundle:Founders:erease }


listServices:
    pattern:  /Servicios/listServices
    defaults: { _controller: CrystalAdminBundle:Services:list }

addServices:
    pattern:  /Servicios/addServices
    defaults: { _controller: CrystalAdminBundle:Services:add }

updateServices:
    pattern:  /Servicios/updateServices/{id}
    defaults: { _controller: CrystalAdminBundle:Services:update }

ereaseServices:
    pattern:  /Servicios/ereaseServices/{id}
    defaults: { _controller: CrystalAdminBundle:Services:erease }